#!/usr/bin/env bash
set -u

job_name="$1"

curl -Ss -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
    https://api.github.com/repos/temporalio/temporal/actions/runs/$GITHUB_RUN_ID/jobs |
    # We use endswith rather than exact name match because, when the workflow is
    # called as a reusable workflow (for example by a calling workflow on a cron
    # schedule), GitHub constructs job names as an (undocumented)
    # slash-separated concatenation of the calling and called job names.
    jq "first(.jobs[] | select(.name | endswith(\"$job_name\")) | .id)"