// The MIT License
//
// Copyright (c) 2020 Temporal Technologies Inc.  All rights reserved.
//
// Copyright (c) 2020 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software" ) to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

package metrics

var (
	ServiceErrUnauthorizedCounter         = NewCounterDef("service_errors_unauthorized")
	ServiceErrAuthorizeFailedCounter      = NewCounterDef("service_errors_authorize_failed")
	ServiceAuthorizationLatency           = NewTimerDef("service_authorization_latency")
	TlsCertsExpired                       = NewGaugeDef("certificates_expired")
	TlsCertsExpiring                      = NewGaugeDef("certificates_expiring")
	NamespaceCachePrepareCallbacksLatency = NewTimerDef("namespace_cache_prepare_callbacks_latency")
	NamespaceCacheCallbacksLatency        = NewTimerDef("namespace_cache_callbacks_latency")
	CacheRequests                         = NewCounterDef("cache_requests")
	CacheFailures                         = NewCounterDef("cache_errors")
	CacheLatency                          = NewTimerDef("cache_latency")
	CacheMissCounter                      = NewCounterDef("cache_miss")
	ActionCounter                         = NewCounterDef("action")
	StateTransitionCount                  = NewDimensionlessHistogramDef("state_transition_count")
	HistorySize                           = NewBytesHistogramDef("history_size")
	HistoryCount                          = NewDimensionlessHistogramDef("history_count")
	ClientRedirectionRequests             = NewCounterDef("client_redirection_requests")
	ClientRedirectionFailures             = NewCounterDef("client_redirection_errors")
	ClientRedirectionLatency              = NewTimerDef("client_redirection_latency")
	VersionCheckSuccessCount              = NewCounterDef("version_check_success")
	VersionCheckFailedCount               = NewCounterDef("version_check_failed")
	VersionCheckRequestFailedCount        = NewCounterDef("version_check_request_failed")
	VersionCheckLatency                   = NewTimerDef("version_check_latency")
	LockRequests                          = NewCounterDef("lock_requests")
	LockFailures                          = NewCounterDef("lock_failures")
	LockLatency                           = NewTimerDef("lock_latency")
	SearchAttributesSize                  = NewBytesHistogramDef("search_attributes_size")

	EventBlobSize                                 = NewBytesHistogramDef("event_blob_size")
	ClientRequests                                = NewCounterDef("client_requests")
	ClientFailures                                = NewCounterDef("client_errors")
	ClientLatency                                 = NewTimerDef("client_latency")
	MatchingClientForwardedCounter                = NewCounterDef("forwarded")
	MatchingClientInvalidTaskQueueName            = NewCounterDef("invalid_task_queue_name")
	ServiceLatency                                = NewTimerDef("service_latency")
	ServiceLatencyNoUserLatency                   = NewTimerDef("service_latency_nouserlatency")
	ServiceLatencyUserLatency                     = NewTimerDef("service_latency_userlatency")
	ServiceRequests                               = NewCounterDef("service_requests")
	ServicePendingRequests                        = NewGaugeDef("service_pending_requests")
	ServiceFailures                               = NewCounterDef("service_errors")
	ServiceErrorWithType                          = NewCounterDef("service_error_with_type")
	ServiceCriticalFailures                       = NewCounterDef("service_errors_critical")
	ServiceErrInvalidArgumentCounter              = NewCounterDef("service_errors_invalid_argument")
	ServiceErrNamespaceNotActiveCounter           = NewCounterDef("service_errors_namespace_not_active")
	ServiceErrResourceExhaustedCounter            = NewCounterDef("service_errors_resource_exhausted")
	ServiceErrNotFoundCounter                     = NewCounterDef("service_errors_entity_not_found")
	ServiceErrExecutionAlreadyStartedCounter      = NewCounterDef("service_errors_execution_already_started")
	ServiceErrNamespaceAlreadyExistsCounter       = NewCounterDef("service_errors_namespace_already_exists")
	ServiceErrCancellationAlreadyRequestedCounter = NewCounterDef("service_errors_cancellation_already_requested")
	ServiceErrQueryFailedCounter                  = NewCounterDef("service_errors_query_failed")
	ServiceErrContextCancelledCounter             = NewCounterDef("service_errors_context_cancelled")
	ServiceErrContextTimeoutCounter               = NewCounterDef("service_errors_context_timeout")
	ServiceErrRetryTaskCounter                    = NewCounterDef("service_errors_retry_task")
	ServiceErrBadBinaryCounter                    = NewCounterDef("service_errors_bad_binary")
	ServiceErrClientVersionNotSupportedCounter    = NewCounterDef("service_errors_client_version_not_supported")
	ServiceErrIncompleteHistoryCounter            = NewCounterDef("service_errors_incomplete_history")
	ServiceErrNonDeterministicCounter             = NewCounterDef("service_errors_nondeterministic")

	NamespaceReplicationDLQMaxLevelGauge                = NewGaugeDef("namespace_dlq_max_level")
	NamespaceReplicationTaskAckLevelGauge               = NewGaugeDef("namespace_replication_task_ack_level")
	PersistenceRequests                                 = NewCounterDef("persistence_requests")
	PersistenceFailures                                 = NewCounterDef("persistence_errors")
	PersistenceErrorWithType                            = NewCounterDef("persistence_error_with_type")
	PersistenceLatency                                  = NewTimerDef("persistence_latency")
	PersistenceErrShardExistsCounter                    = NewCounterDef("persistence_errors_shard_exists")
	PersistenceErrShardOwnershipLostCounter             = NewCounterDef("persistence_errors_shard_ownership_lost")
	PersistenceErrConditionFailedCounter                = NewCounterDef("persistence_errors_condition_failed")
	PersistenceErrCurrentWorkflowConditionFailedCounter = NewCounterDef("persistence_errors_current_workflow_condition_failed")
	PersistenceErrWorkflowConditionFailedCounter        = NewCounterDef("persistence_errors_workflow_condition_failed")
	PersistenceErrTimeoutCounter                        = NewCounterDef("persistence_errors_timeout")
	PersistenceErrBusyCounter                           = NewCounterDef("persistence_errors_busy")
	PersistenceErrEntityNotExistsCounter                = NewCounterDef("persistence_errors_entity_not_exists")
	PersistenceErrNamespaceAlreadyExistsCounter         = NewCounterDef("persistence_errors_namespace_already_exists")
	PersistenceErrBadRequestCounter                     = NewCounterDef("persistence_errors_bad_request")
	PersistenceErrResourceExhaustedCounter              = NewCounterDef("persistence_errors_resource_exhausted")
	ElasticsearchBulkProcessorRequests                  = NewCounterDef("elasticsearch_bulk_processor_requests")
	ElasticsearchBulkProcessorQueuedRequests            = NewDimensionlessHistogramDef("elasticsearch_bulk_processor_queued_requests")
	ElasticsearchBulkProcessorRetries                   = NewCounterDef("elasticsearch_bulk_processor_retries")
	ElasticsearchBulkProcessorFailures                  = NewCounterDef("elasticsearch_bulk_processor_errors")
	ElasticsearchBulkProcessorCorruptedData             = NewCounterDef("elasticsearch_bulk_processor_corrupted_data")
	ElasticsearchBulkProcessorDuplicateRequest          = NewCounterDef("elasticsearch_bulk_processor_duplicate_request")
	ElasticsearchBulkProcessorRequestLatency            = NewTimerDef("elasticsearch_bulk_processor_request_latency")
	ElasticsearchBulkProcessorCommitLatency             = NewTimerDef("elasticsearch_bulk_processor_commit_latency")
	ElasticsearchBulkProcessorWaitAddLatency            = NewTimerDef("elasticsearch_bulk_processor_wait_add_latency")
	ElasticsearchBulkProcessorWaitStartLatency          = NewTimerDef("elasticsearch_bulk_processor_wait_start_latency")
	ElasticsearchBulkProcessorBulkSize                  = NewDimensionlessHistogramDef("elasticsearch_bulk_processor_bulk_size")
	ElasticsearchDocumentParseFailuresCount             = NewCounterDef("elasticsearch_document_parse_failures_counter")
	ElasticsearchDocumentGenerateFailuresCount          = NewCounterDef("elasticsearch_document_generate_failures_counter")
	VisibilityPersistenceRequests                       = NewCounterDef("visibility_persistence_requests")
	VisibilityPersistenceErrorWithType                  = NewCounterDef("visibility_persistence_error_with_type")
	VisibilityPersistenceFailures                       = NewCounterDef("visibility_persistence_errors")
	VisibilityPersistenceResourceExhausted              = NewCounterDef("visibility_persistence_resource_exhausted")
	VisibilityPersistenceLatency                        = NewTimerDef("visibility_persistence_latency")

	StartedCount                                              = NewCounterDef("started")
	StoppedCount                                              = NewCounterDef("stopped")
	ExecutorTasksDoneCount                                    = NewCounterDef("executor_done")
	ExecutorTasksErrCount                                     = NewCounterDef("executor_err")
	ExecutorTasksDeferredCount                                = NewCounterDef("executor_deferred")
	ExecutorTasksDroppedCount                                 = NewCounterDef("executor_dropped")
	ScavengerValidationRequestsCount                          = NewCounterDef("scavenger_validation_requests")
	ScavengerValidationFailuresCount                          = NewCounterDef("scavenger_validation_failures")
	HistoryScavengerSuccessCount                              = NewCounterDef("scavenger_success")
	HistoryScavengerErrorCount                                = NewCounterDef("scavenger_errors")
	HistoryScavengerSkipCount                                 = NewCounterDef("scavenger_skips")
	ExecutionsOutstandingCount                                = NewGaugeDef("executions_outstanding")
	TaskProcessedCount                                        = NewGaugeDef("task_processed")
	TaskDeletedCount                                          = NewGaugeDef("task_deleted")
	TaskQueueProcessedCount                                   = NewGaugeDef("taskqueue_processed")
	TaskQueueDeletedCount                                     = NewGaugeDef("taskqueue_deleted")
	TaskQueueOutstandingCount                                 = NewGaugeDef("taskqueue_outstanding")
	HistoryArchiverArchiveNonRetryableErrorCount              = NewCounterDef("history_archiver_archive_non_retryable_error")
	HistoryArchiverArchiveTransientErrorCount                 = NewCounterDef("history_archiver_archive_transient_error")
	HistoryArchiverArchiveSuccessCount                        = NewCounterDef("history_archiver_archive_success")
	HistoryArchiverHistoryMutatedCount                        = NewCounterDef("history_archiver_history_mutated")
	HistoryArchiverTotalUploadSize                            = NewBytesHistogramDef("history_archiver_total_upload_size")
	HistoryArchiverHistorySize                                = NewBytesHistogramDef("history_archiver_history_size")
	HistoryArchiverDuplicateArchivalsCount                    = NewCounterDef("history_archiver_duplicate_archivals")
	HistoryArchiverBlobExistsCount                            = NewCounterDef("history_archiver_blob_exists")
	HistoryArchiverBlobSize                                   = NewBytesHistogramDef("history_archiver_blob_size")
	HistoryArchiverRunningDeterministicConstructionCheckCount = NewCounterDef("history_archiver_running_deterministic_construction_check")
	HistoryArchiverDeterministicConstructionCheckFailedCount  = NewCounterDef("history_archiver_deterministic_construction_check_failed")
	HistoryArchiverRunningBlobIntegrityCheckCount             = NewCounterDef("history_archiver_running_blob_integrity_check")
	HistoryArchiverBlobIntegrityCheckFailedCount              = NewCounterDef("history_archiver_blob_integrity_check_failed")
	VisibilityArchiverArchiveNonRetryableErrorCount           = NewCounterDef("visibility_archiver_archive_non_retryable_error")
	VisibilityArchiverArchiveTransientErrorCount              = NewCounterDef("visibility_archiver_archive_transient_error")
	VisibilityArchiveSuccessCount                             = NewCounterDef("visibility_archiver_archive_success")
	BatcherProcessorSuccess                                   = NewCounterDef("batcher_processor_requests")
	BatcherProcessorFailures                                  = NewCounterDef("batcher_processor_errors")
	DeleteNamespaceSuccessCount                               = NewCounterDef("delete_namespace_success")
	RenameNamespaceSuccessCount                               = NewCounterDef("rename_namespace_success")
	DeleteExecutionsSuccessCount                              = NewCounterDef("delete_executions_success")
	DeleteNamespaceFailuresCount                              = NewCounterDef("delete_namespace_failures")
	UpdateNamespaceFailuresCount                              = NewCounterDef("update_namespace_failures")
	RenameNamespaceFailuresCount                              = NewCounterDef("rename_namespace_failures")
	ReadNamespaceFailuresCount                                = NewCounterDef("read_namespace_failures")
	ListExecutionsFailuresCount                               = NewCounterDef("list_executions_failures")
	CountExecutionsFailuresCount                              = NewCounterDef("count_executions_failures")
	DeleteExecutionFailuresCount                              = NewCounterDef("delete_execution_failures")
	DeleteExecutionNotFoundCount                              = NewCounterDef("delete_execution_not_found")
	RateLimiterFailuresCount                                  = NewCounterDef("rate_limiter_failures")
	AddSearchAttributesFailuresCount                          = NewCounterDef("add_search_attributes_failures")
	ArchiverNonRetryableErrorCount                            = NewCounterDef("archiver_non_retryable_error")
	ArchiverStartedCount                                      = NewCounterDef("archiver_started")
	ArchiverStoppedCount                                      = NewCounterDef("archiver_stopped")
	ArchiverCoroutineStartedCount                             = NewCounterDef("archiver_coroutine_started")
	ArchiverCoroutineStoppedCount                             = NewCounterDef("archiver_coroutine_stopped")
	ArchiverHandleHistoryRequestLatency                       = NewTimerDef("archiver_handle_history_request_latency")
	ArchiverHandleVisibilityRequestLatency                    = NewTimerDef("archiver_handle_visibility_request_latency")
	ArchiverUploadWithRetriesLatency                          = NewTimerDef("archiver_upload_with_retries_latency")
	ArchiverDeleteWithRetriesLatency                          = NewTimerDef("archiver_delete_with_retries_latency")
	ArchiverUploadFailedAllRetriesCount                       = NewCounterDef("archiver_upload_failed_all_retries")
	ArchiverUploadSuccessCount                                = NewCounterDef("archiver_upload_success")
	ArchiverDeleteFailedAllRetriesCount                       = NewCounterDef("archiver_delete_failed_all_retries")
	ArchiverDeleteSuccessCount                                = NewCounterDef("archiver_delete_success")
	ArchiverHandleVisibilityFailedAllRetiresCount             = NewCounterDef("archiver_handle_visibility_failed_all_retries")
	ArchiverHandleVisibilitySuccessCount                      = NewCounterDef("archiver_handle_visibility_success")
	ArchiverBacklogSizeGauge                                  = NewCounterDef("archiver_backlog_size")
	ArchiverPumpTimeoutCount                                  = NewCounterDef("archiver_pump_timeout")
	ArchiverPumpSignalThresholdCount                          = NewCounterDef("archiver_pump_signal_threshold")
	ArchiverPumpTimeoutWithoutSignalsCount                    = NewCounterDef("archiver_pump_timeout_without_signals")
	ArchiverPumpSignalChannelClosedCount                      = NewCounterDef("archiver_pump_signal_channel_closed")
	ArchiverWorkflowStartedCount                              = NewCounterDef("archiver_workflow_started")
	ArchiverNumPumpedRequestsCount                            = NewCounterDef("archiver_num_pumped_requests")
	ArchiverNumHandledRequestsCount                           = NewCounterDef("archiver_num_handled_requests")
	ArchiverPumpedNotEqualHandledCount                        = NewCounterDef("archiver_pumped_not_equal_handled")
	ArchiverHandleAllRequestsLatency                          = NewTimerDef("archiver_handle_all_requests_latency")
	ArchiverWorkflowStoppingCount                             = NewCounterDef("archiver_workflow_stopping")
	ArchiverClientSendSignalCount                             = NewCounterDef("archiver_client_sent_signal")
	ArchiverClientSendSignalFailureCount                      = NewCounterDef("archiver_client_send_signal_error")
	ArchiverClientHistoryRequestCount                         = NewCounterDef("archiver_client_history_request")
	ArchiverClientHistoryInlineArchiveAttemptCount            = NewCounterDef("archiver_client_history_inline_archive_attempt")
	ArchiverClientHistoryInlineArchiveFailureCount            = NewCounterDef("archiver_client_history_inline_archive_failure")
	ArchiverClientVisibilityRequestCount                      = NewCounterDef("archiver_client_visibility_request")
	ArchiverClientVisibilityInlineArchiveAttemptCount         = NewCounterDef("archiver_client_visibility_inline_archive_attempt")
	ArchiverClientVisibilityInlineArchiveFailureCount         = NewCounterDef("archiver_client_visibility_inline_archive_failure")
	ReplicatorMessages                                        = NewCounterDef("replicator_messages")
	ReplicatorFailures                                        = NewCounterDef("replicator_errors")
	ReplicatorLatency                                         = NewTimerDef("replicator_latency")
	ReplicatorDLQFailures                                     = NewCounterDef("replicator_dlq_enqueue_fails")
	ScanDuration                                              = NewTimerDef("scan_duration")
	NamespaceReplicationEnqueueDLQCount                       = NewCounterDef("namespace_replication_dlq_enqueue_requests")
	CatchUpReadyShardCountGauge                               = NewGaugeDef("catchup_ready_shard_count")
	HandoverReadyShardCountGauge                              = NewGaugeDef("handover_ready_shard_count")
	ParentClosePolicyProcessorSuccess                         = NewCounterDef("parent_close_policy_processor_requests")
	ParentClosePolicyProcessorFailures                        = NewCounterDef("parent_close_policy_processor_errors")

	HistoryEventNotificationQueueingLatency      = NewTimerDef("history_event_notification_queueing_latency")
	HistoryEventNotificationFanoutLatency        = NewTimerDef("history_event_notification_fanout_latency")
	HistoryEventNotificationInFlightMessageGauge = NewGaugeDef("history_event_notification_inflight_message_gauge")
	HistoryEventNotificationFailDeliveryCount    = NewCounterDef("history_event_notification_fail_delivery_count")

	AddSearchAttributesWorkflowSuccessCount  = NewCounterDef("add_search_attributes_workflow_success")
	AddSearchAttributesWorkflowFailuresCount = NewCounterDef("add_search_attributes_workflow_failure")

	DeleteNamespaceWorkflowSuccessCount  = NewCounterDef("delete_namespace_workflow_success")
	DeleteNamespaceWorkflowFailuresCount = NewCounterDef("delete_namespace_workflow_failure")
)

// Matching
var (
	PollSuccessPerTaskQueueCounter            = NewRollupCounterDef("poll_success_per_tl", "poll_success")
	PollTimeoutPerTaskQueueCounter            = NewRollupCounterDef("poll_timeouts_per_tl", "poll_timeouts")
	PollSuccessWithSyncPerTaskQueueCounter    = NewRollupCounterDef("poll_success_sync_per_tl", "poll_success_sync")
	LeaseRequestPerTaskQueueCounter           = NewRollupCounterDef("lease_requests_per_tl", "lease_requests")
	LeaseFailurePerTaskQueueCounter           = NewRollupCounterDef("lease_failures_per_tl", "lease_failures")
	ConditionFailedErrorPerTaskQueueCounter   = NewRollupCounterDef("condition_failed_errors_per_tl", "condition_failed_errors")
	RespondQueryTaskFailedPerTaskQueueCounter = NewRollupCounterDef("respond_query_failed_per_tl", "respond_query_failed")
	SyncThrottlePerTaskQueueCounter           = NewRollupCounterDef("sync_throttle_count_per_tl", "sync_throttle_count")
	BufferThrottlePerTaskQueueCounter         = NewRollupCounterDef("buffer_throttle_count_per_tl", "buffer_throttle_count")
	ExpiredTasksPerTaskQueueCounter           = NewRollupCounterDef("tasks_expired_per_tl", "tasks_expired")
	ForwardedPerTaskQueueCounter              = NewCounterDef("forwarded_per_tl")
	ForwardTaskCallsPerTaskQueue              = NewRollupCounterDef("forward_task_calls_per_tl", "forward_task_calls")
	ForwardTaskErrorsPerTaskQueue             = NewRollupCounterDef("forward_task_errors_per_tl", "forward_task_errors")
	ForwardQueryCallsPerTaskQueue             = NewRollupCounterDef("forward_query_calls_per_tl", "forward_query_calls")
	ForwardQueryErrorsPerTaskQueue            = NewRollupCounterDef("forward_query_errors_per_tl", "forward_query_errors")
	ForwardPollCallsPerTaskQueue              = NewRollupCounterDef("forward_poll_calls_per_tl", "forward_poll_calls")
	ForwardPollErrorsPerTaskQueue             = NewRollupCounterDef("forward_poll_errors_per_tl", "forward_poll_errors")
	SyncMatchLatencyPerTaskQueue              = NewRollupTimerDef("syncmatch_latency_per_tl", "syncmatch_latency")
	AsyncMatchLatencyPerTaskQueue             = NewRollupTimerDef("asyncmatch_latency_per_tl", "asyncmatch_latency")
	ForwardTaskLatencyPerTaskQueue            = NewRollupTimerDef("forward_task_latency_per_tl", "forward_task_latency")
	ForwardQueryLatencyPerTaskQueue           = NewRollupTimerDef("forward_query_latency_per_tl", "forward_query_latency")
	ForwardPollLatencyPerTaskQueue            = NewRollupTimerDef("forward_poll_latency_per_tl", "forward_poll_latency")
	LocalToLocalMatchPerTaskQueueCounter      = NewRollupCounterDef("local_to_local_matches_per_tl", "local_to_local_matches")
	LocalToRemoteMatchPerTaskQueueCounter     = NewRollupCounterDef("local_to_remote_matches_per_tl", "local_to_remote_matches")
	RemoteToLocalMatchPerTaskQueueCounter     = NewRollupCounterDef("remote_to_local_matches_per_tl", "remote_to_local_matches")
	RemoteToRemoteMatchPerTaskQueueCounter    = NewRollupCounterDef("remote_to_remote_matches_per_tl", "remote_to_remote_matches")
	LoadedTaskQueueGauge                      = NewGaugeDef("loaded_task_queue_count")
	TaskQueueStartedCounter                   = NewCounterDef("task_queue_started")
	TaskQueueStoppedCounter                   = NewCounterDef("task_queue_stopped")
	TaskWriteThrottlePerTaskQueueCounter      = NewRollupCounterDef("task_write_throttle_count_per_tl", "task_write_throttle_count")
	TaskWriteLatencyPerTaskQueue              = NewRollupTimerDef("task_write_latency_per_tl", "task_write_latency")
	TaskLagPerTaskQueueGauge                  = NewGaugeDef("task_lag_per_tl")
	NoRecentPollerTasksPerTaskQueueCounter    = NewRollupCounterDef("no_poller_tasks_per_tl", "no_poller_tasks")
)

// History
var (
	TaskRequests = NewCounterDef("task_requests")

	TaskLatency       = NewTimerDef("task_latency")               // overall/all attempts within single worker
	TaskUserLatency   = NewTimerDef("task_latency_userlatency")   // from task generated to task complete
	TaskNoUserLatency = NewTimerDef("task_latency_nouserlatency") // from task generated to task complete

	TaskAttemptTimer         = NewDimensionlessHistogramDef("task_attempt")
	TaskFailures             = NewCounterDef("task_errors")
	TaskDiscarded            = NewCounterDef("task_errors_discarded")
	TaskSkipped              = NewCounterDef("task_skipped")
	TaskStandbyRetryCounter  = NewCounterDef("task_errors_standby_retry_counter")
	TaskWorkflowBusyCounter  = NewCounterDef("task_errors_workflow_busy")
	TaskNotActiveCounter     = NewCounterDef("task_errors_not_active_counter")
	TaskLimitExceededCounter = NewCounterDef("task_errors_limit_exceeded_counter")

	TaskScheduleToStartLatency = NewTimerDef("task_schedule_to_start_latency")

	TaskProcessingLatency       = NewTimerDef("task_latency_processing")               // per-attempt
	TaskNoUserProcessingLatency = NewTimerDef("task_latency_processing_nouserlatency") // per-attempt

	TaskQueueLatency       = NewTimerDef("task_latency_queue")               // from task generated to task complete
	TaskNoUserQueueLatency = NewTimerDef("task_latency_queue_nouserlatency") // from task generated to task complete

	TransferTaskMissingEventCounter                  = NewCounterDef("transfer_task_missing_event_counter")
	TaskBatchCompleteCounter                         = NewCounterDef("task_batch_complete_counter")
	TaskReschedulerPendingTasks                      = NewDimensionlessHistogramDef("task_rescheduler_pending_tasks")
	TaskThrottledCounter                             = NewCounterDef("task_throttled_counter")
	ActivityE2ELatency                               = NewTimerDef("activity_end_to_end_latency")
	AckLevelUpdateCounter                            = NewCounterDef("ack_level_update")
	AckLevelUpdateFailedCounter                      = NewCounterDef("ack_level_update_failed")
	CommandTypeScheduleActivityCounter               = NewCounterDef("schedule_activity_command")
	CommandTypeCompleteWorkflowCounter               = NewCounterDef("complete_workflow_command")
	CommandTypeFailWorkflowCounter                   = NewCounterDef("fail_workflow_command")
	CommandTypeCancelWorkflowCounter                 = NewCounterDef("cancel_workflow_command")
	CommandTypeStartTimerCounter                     = NewCounterDef("start_timer_command")
	CommandTypeCancelActivityCounter                 = NewCounterDef("cancel_activity_command")
	CommandTypeCancelTimerCounter                    = NewCounterDef("cancel_timer_command")
	CommandTypeRecordMarkerCounter                   = NewCounterDef("record_marker_command")
	CommandTypeCancelExternalWorkflowCounter         = NewCounterDef("cancel_external_workflow_command")
	CommandTypeContinueAsNewCounter                  = NewCounterDef("continue_as_new_command")
	CommandTypeSignalExternalWorkflowCounter         = NewCounterDef("signal_external_workflow_command")
	CommandTypeUpsertWorkflowSearchAttributesCounter = NewCounterDef("upsert_workflow_search_attributes_command")
	CommandTypeModifyWorkflowPropertiesCounter       = NewCounterDef("modify_workflow_properties_command")
	CommandTypeChildWorkflowCounter                  = NewCounterDef("child_workflow_command")
	ActivityEagerExecutionCounter                    = NewCounterDef("activity_eager_execution")
	EmptyCompletionCommandsCounter                   = NewCounterDef("empty_completion_commands")
	MultipleCompletionCommandsCounter                = NewCounterDef("multiple_completion_commands")
	FailedWorkflowTasksCounter                       = NewCounterDef("failed_workflow_tasks")
	WorkflowTaskAttempt                              = NewDimensionlessHistogramDef("workflow_task_attempt")
	StaleMutableStateCounter                         = NewCounterDef("stale_mutable_state")
	AutoResetPointsLimitExceededCounter              = NewCounterDef("auto_reset_points_exceed_limit")
	AutoResetPointCorruptionCounter                  = NewCounterDef("auto_reset_point_corruption")
	ConcurrencyUpdateFailureCounter                  = NewCounterDef("concurrency_update_failure")
	ServiceErrShardOwnershipLostCounter              = NewCounterDef("service_errors_shard_ownership_lost")
	ServiceErrTaskAlreadyStartedCounter              = NewCounterDef("service_errors_task_already_started")
	HeartbeatTimeoutCounter                          = NewCounterDef("heartbeat_timeout")
	ScheduleToStartTimeoutCounter                    = NewCounterDef("schedule_to_start_timeout")
	StartToCloseTimeoutCounter                       = NewCounterDef("start_to_close_timeout")
	ScheduleToCloseTimeoutCounter                    = NewCounterDef("schedule_to_close_timeout")
	NewTimerNotifyCounter                            = NewCounterDef("new_timer_notifications")
	AcquireShardsCounter                             = NewCounterDef("acquire_shards_count")
	AcquireShardsLatency                             = NewTimerDef("acquire_shards_latency")
	ShardContextClosedCounter                        = NewCounterDef("shard_closed_count")
	ShardContextCreatedCounter                       = NewCounterDef("sharditem_created_count")
	ShardContextRemovedCounter                       = NewCounterDef("sharditem_removed_count")
	ShardContextAcquisitionLatency                   = NewTimerDef("sharditem_acquisition_latency")
	ShardInfoReplicationPendingTasksTimer            = NewDimensionlessHistogramDef("shardinfo_replication_pending_task")
	ShardInfoTransferActivePendingTasksTimer         = NewDimensionlessHistogramDef("shardinfo_transfer_active_pending_task")
	ShardInfoTransferStandbyPendingTasksTimer        = NewDimensionlessHistogramDef("shardinfo_transfer_standby_pending_task")
	ShardInfoTimerActivePendingTasksTimer            = NewDimensionlessHistogramDef("shardinfo_timer_active_pending_task")
	ShardInfoTimerStandbyPendingTasksTimer           = NewDimensionlessHistogramDef("shardinfo_timer_standby_pending_task")
	ShardInfoVisibilityPendingTasksTimer             = NewDimensionlessHistogramDef("shardinfo_visibility_pending_task")
	ShardInfoReplicationLagHistogram                 = NewDimensionlessHistogramDef("shardinfo_replication_lag")
	ShardInfoTransferLagHistogram                    = NewDimensionlessHistogramDef("shardinfo_transfer_lag")
	ShardInfoTimerLagTimer                           = NewTimerDef("shardinfo_timer_lag")
	ShardInfoVisibilityLagHistogram                  = NewDimensionlessHistogramDef("shardinfo_visibility_lag")
	ShardInfoTransferDiffHistogram                   = NewDimensionlessHistogramDef("shardinfo_transfer_diff")
	ShardInfoTimerDiffTimer                          = NewTimerDef("shardinfo_timer_diff")
	ShardInfoTransferFailoverInProgressHistogram     = NewDimensionlessHistogramDef("shardinfo_transfer_failover_in_progress")
	ShardInfoTimerFailoverInProgressHistogram        = NewDimensionlessHistogramDef("shardinfo_timer_failover_in_progress")
	ShardInfoTransferFailoverLatencyTimer            = NewTimerDef("shardinfo_transfer_failover_latency")
	ShardInfoTimerFailoverLatencyTimer               = NewTimerDef("shardinfo_timer_failover_latency")
	SyncShardFromRemoteCounter                       = NewCounterDef("syncshard_remote_count")
	SyncShardFromRemoteFailure                       = NewCounterDef("syncshard_remote_failed")
	MembershipChangedCounter                         = NewCounterDef("membership_changed_count")
	NumShardsGauge                                   = NewGaugeDef("numshards_gauge")
	GetEngineForShardErrorCounter                    = NewCounterDef("get_engine_for_shard_errors")
	GetEngineForShardLatency                         = NewTimerDef("get_engine_for_shard_latency")
	RemoveEngineForShardLatency                      = NewTimerDef("remove_engine_for_shard_latency")
	CompleteWorkflowTaskWithStickyEnabledCounter     = NewCounterDef("complete_workflow_task_sticky_enabled_count")
	CompleteWorkflowTaskWithStickyDisabledCounter    = NewCounterDef("complete_workflow_task_sticky_disabled_count")
	WorkflowTaskHeartbeatTimeoutCounter              = NewCounterDef("workflow_task_heartbeat_timeout_count")
	EmptyReplicationEventsCounter                    = NewCounterDef("empty_replication_events")
	DuplicateReplicationEventsCounter                = NewCounterDef("duplicate_replication_events")
	StaleReplicationEventsCounter                    = NewCounterDef("stale_replication_events")
	ReplicationEventsSizeTimer                       = NewTimerDef("replication_events_size")
	BufferReplicationTaskTimer                       = NewTimerDef("buffer_replication_tasks")
	UnbufferReplicationTaskTimer                     = NewTimerDef("unbuffer_replication_tasks")
	HistoryConflictsCounter                          = NewCounterDef("history_conflicts")
	CompleteTaskFailedCounter                        = NewCounterDef("complete_task_fail_count")
	AcquireLockFailedCounter                         = NewCounterDef("acquire_lock_failed")
	WorkflowContextCleared                           = NewCounterDef("workflow_context_cleared")
	MutableStateSize                                 = NewBytesHistogramDef("mutable_state_size")
	ExecutionInfoSize                                = NewBytesHistogramDef("execution_info_size")
	ExecutionStateSize                               = NewBytesHistogramDef("execution_state_size")
	ActivityInfoSize                                 = NewBytesHistogramDef("activity_info_size")
	TimerInfoSize                                    = NewBytesHistogramDef("timer_info_size")
	ChildInfoSize                                    = NewBytesHistogramDef("child_info_size")
	RequestCancelInfoSize                            = NewBytesHistogramDef("request_cancel_info_size")
	SignalInfoSize                                   = NewBytesHistogramDef("signal_info_size")
	BufferedEventsSize                               = NewBytesHistogramDef("buffered_events_size")
	ActivityInfoCount                                = NewDimensionlessHistogramDef("activity_info_count")
	TimerInfoCount                                   = NewDimensionlessHistogramDef("timer_info_count")
	ChildInfoCount                                   = NewDimensionlessHistogramDef("child_info_count")
	SignalInfoCount                                  = NewDimensionlessHistogramDef("signal_info_count")
	RequestCancelInfoCount                           = NewDimensionlessHistogramDef("request_cancel_info_count")
	BufferedEventsCount                              = NewDimensionlessHistogramDef("buffered_events_count")
	TaskCount                                        = NewDimensionlessHistogramDef("task_count")
	WorkflowRetryBackoffTimerCount                   = NewCounterDef("workflow_retry_backoff_timer")
	WorkflowCronBackoffTimerCount                    = NewCounterDef("workflow_cron_backoff_timer")
	WorkflowCleanupDeleteCount                       = NewCounterDef("workflow_cleanup_delete")
	WorkflowCleanupArchiveCount                      = NewCounterDef("workflow_cleanup_archive")
	WorkflowCleanupNopCount                          = NewCounterDef("workflow_cleanup_nop")
	WorkflowCleanupDeleteHistoryInlineCount          = NewCounterDef("workflow_cleanup_delete_history_inline")
	WorkflowSuccessCount                             = NewCounterDef("workflow_success")
	WorkflowCancelCount                              = NewCounterDef("workflow_cancel")
	WorkflowFailedCount                              = NewCounterDef("workflow_failed")
	WorkflowTimeoutCount                             = NewCounterDef("workflow_timeout")
	WorkflowTerminateCount                           = NewCounterDef("workflow_terminate")
	WorkflowContinuedAsNewCount                      = NewCounterDef("workflow_continued_as_new")
	LastRetrievedMessageID                           = NewGaugeDef("last_retrieved_message_id")
	LastProcessedMessageID                           = NewGaugeDef("last_processed_message_id")
	ReplicationTasksApplied                          = NewCounterDef("replication_tasks_applied")
	ReplicationTasksFailed                           = NewCounterDef("replication_tasks_failed")
	ReplicationTasksLag                              = NewTimerDef("replication_tasks_lag")
	ReplicationLatency                               = NewTimerDef("replication_latency")
	ReplicationTasksFetched                          = NewTimerDef("replication_tasks_fetched")
	ReplicationTasksReturned                         = NewTimerDef("replication_tasks_returned")
	ReplicationTasksAppliedLatency                   = NewTimerDef("replication_tasks_applied_latency")
	ReplicationDLQFailed                             = NewCounterDef("replication_dlq_enqueue_failed")
	ReplicationDLQMaxLevelGauge                      = NewGaugeDef("replication_dlq_max_level")
	ReplicationDLQAckLevelGauge                      = NewGaugeDef("replication_dlq_ack_level")
	GetReplicationMessagesForShardLatency            = NewTimerDef("get_replication_messages_for_shard")
	GetDLQReplicationMessagesLatency                 = NewTimerDef("get_dlq_replication_messages")
	EventReapplySkippedCount                         = NewCounterDef("event_reapply_skipped_count")
	DirectQueryDispatchLatency                       = NewTimerDef("direct_query_dispatch_latency")
	DirectQueryDispatchStickyLatency                 = NewTimerDef("direct_query_dispatch_sticky_latency")
	DirectQueryDispatchNonStickyLatency              = NewTimerDef("direct_query_dispatch_non_sticky_latency")
	DirectQueryDispatchStickySuccessCount            = NewCounterDef("direct_query_dispatch_sticky_success")
	DirectQueryDispatchNonStickySuccessCount         = NewCounterDef("direct_query_dispatch_non_sticky_success")
	DirectQueryDispatchClearStickinessLatency        = NewTimerDef("direct_query_dispatch_clear_stickiness_latency")
	DirectQueryDispatchClearStickinessSuccessCount   = NewCounterDef("direct_query_dispatch_clear_stickiness_success")
	DirectQueryDispatchTimeoutBeforeNonStickyCount   = NewCounterDef("direct_query_dispatch_timeout_before_non_sticky")
	WorkflowTaskQueryLatency                         = NewTimerDef("workflow_task_query_latency")
	ConsistentQueryTimeoutCount                      = NewCounterDef("consistent_query_timeout")
	QueryBeforeFirstWorkflowTaskCount                = NewCounterDef("query_before_first_workflow_task")
	QueryBufferExceededCount                         = NewCounterDef("query_buffer_exceeded")
	QueryRegistryInvalidStateCount                   = NewCounterDef("query_registry_invalid_state")
	WorkerNotSupportsConsistentQueryCount            = NewCounterDef("worker_not_supports_consistent_query")
	WorkflowTaskTimeoutOverrideCount                 = NewCounterDef("workflow_task_timeout_overrides")
	WorkflowRunTimeoutOverrideCount                  = NewCounterDef("workflow_run_timeout_overrides")
	ReplicationTaskCleanupCount                      = NewCounterDef("replication_task_cleanup_count")
	ReplicationTaskCleanupFailure                    = NewCounterDef("replication_task_cleanup_failed")
	MutableStateChecksumMismatch                     = NewCounterDef("mutable_state_checksum_mismatch")
	MutableStateChecksumInvalidated                  = NewCounterDef("mutable_state_checksum_invalidated")
)
