frontend.validSearchAttributes:
- value:
    NamespaceID: 1
  constraints: {}
testGetBoolPropertyKey:
- value: false
  constraints: {}
- value: true
  constraints:
    namespace: global-samples-namespace
- value: true
  constraints:
    namespace: samples-namespace
testGetDurationPropertyKey:
- value: 1m
  constraints: {}
- value: wrong duration string
  constraints:
    namespace: samples-namespace
    taskListName: longIdleTimeTasklist
- value: 2
  constraints:
    namespace: samples-namespace
testGetFloat64PropertyKey:
- value: 12
  constraints: {}
- value: wrong type
  constraints:
    namespace: samples-namespace
testGetIntPropertyKey:
- value: 1000
  constraints: {}
- value: 1000.1
  constraints:
    namespace: global-samples-namespace
testGetMapPropertyKey:
- value:
    key1: "1"
    key2: 1
    key3:
    - false
    - key4: true
      key5: 2.1
  constraints: {}
- value: "1"
  constraints:
    taskListName: random tasklist
testGetStringPropertyKey:
- value: some random string
  constraints: {}
- value: constrained-string
  constraints:
    taskListName: random tasklist
