name: Docker Compose Stop
description: Stop Docker Compose services.

inputs:
  compose_file:
    description: Docker Compose file to use.
    required: true
  flags:
    description: Additional options to pass to docker compose down.
    default: ""

runs:
  using: composite
  steps:
    - name: Stop services
      shell: bash
      env:
        COMPOSE_FILE: ${{ inputs.compose_file }}
        FLAGS: ${{ inputs.flags }}
      run: |
        docker compose -f "$COMPOSE_FILE" down $FLAGS
