package telemetry

const (
	ComponentPersistence     = "temporalPersistence"
	ComponentQueueArchival   = "temporalQueueArchival"
	ComponentQueueMemory     = "temporalQueueMemory"
	ComponentQueueOutbound   = "temporalQueueOutbound"
	ComponentQueueTimer      = "temporalQueueTimer"
	ComponentQueueTransfer   = "temporalQueueTransfer"
	ComponentQueueVisibility = "temporalQueueVisibility"
	ComponentUpdateRegistry  = "temporalUpdateRegistry"
)

const (
	BusinessIDKey                 = "temporalBusinessID"
	ChasmArchetypeIDKey           = "temporalChasmArchetypeID"
	ChasmTransitionDestinationKey = "temporalChasmTransitionDestination"
	ChasmTransitionErrorKey       = "temporalChasmTransitionError"
	ChasmTransitionSourceKey      = "temporalChasmTransitionSource"
	NamespaceIDKey                = "temporalNamespaceID"
	NamespaceKey                  = "temporalNamespace"
	NexusEndpointKey              = "temporalNexusEndpoint"
	NexusHandlerNamespaceKey      = "temporalNexusHandlerNamespace"
	NexusHandlerRunIDKey          = "temporalNexusHandlerRunID"
	NexusHandlerWorkflowIDKey     = "temporalNexusHandlerWorkflowID"
	NexusNamespaceKey             = "temporalNexusNamespace"
	NexusOperationKey             = "temporalNexusOperation"
	NexusRequestIDKey             = "temporalNexusRequestID"
	NexusServiceKey               = "temporalNexusService"
	PersistenceMethodKey          = "temporalPersistenceMethod"
	PersistenceRequestPayloadKey  = "temporalPersistenceRequestPayload"
	PersistenceResponsePayloadKey = "temporalPersistenceResponsePayload"
	PersistenceStoreKey           = "temporalPersistenceStore"
	QueueTaskIDKey                = "temporalQueueTaskID"
	QueueTaskPayloadKey           = "temporalQueueTaskPayload"
	QueueTaskTypeKey              = "temporalQueueTaskType"
	RunIDKey                      = "temporalRunID"
	WorkerTaskIDKey               = "temporalWorkerTaskID"
	WorkflowIDKey                 = "temporalWorkflowID"
)
