# https://golangci-lint.run/usage/configuration/#config-file
linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - revive # revive supersedes golint, which is now archived
    - staticcheck
    - vet
run:
  skip-dirs:
    - api
    - proto
issues:
  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  # It's a super-useful option for integration of golangci-lint into existing large codebase.
  # It's not practical to fix all existing issues at the moment of integration:
  # much better don't allow issues in new code.
  new: true
  # Fix found issues (if it's supported by the linter).
  fix: true
