before:
  hooks:
    - go mod download
    - ./develop/scripts/create_build_info_data.sh
builds:
  - id: "temporal-server"
    dir: cmd/server
    binary: temporal-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: "tctl"
    dir: cmd/tools/cli
    binary: tctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: "temporal-cassandra-tool"
    dir: cmd/tools/cassandra
    binary: temporal-cassandra-tool
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: "temporal-sql-tool"
    dir: cmd/tools/sql
    binary: temporal-sql-tool
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
