package tests

import "testing"

// FunctionalTestEntry identifies one root functional test that can be run
// through [Run].
type FunctionalTestEntry struct {
	Name string

	run func(*testing.T)
}

var functionalTestEntries = []FunctionalTestEntry{
	{Name: "TestAcquireShardSuite", run: runTestAcquireShardSuite},
	{Name: "TestActivityAPIBatchCancelClientTestSuite", run: runTestActivityAPIBatchCancelClientTestSuite},
	{Name: "TestActivityAPIBatchDeleteClientTestSuite", run: runTestActivityAPIBatchDeleteClientTestSuite},
	{Name: "TestActivityAPIBatchResetClientTestSuite", run: runTestActivityAPIBatchResetClientTestSuite},
	{Name: "TestActivityAPIBatchSecurityTestSuite", run: runTestActivityAPIBatchSecurityTestSuite},
	{Name: "TestActivityAPIBatchTerminateClientTestSuite", run: runTestActivityAPIBatchTerminateClientTestSuite},
	{Name: "TestActivityApiBatchUnpauseClientTestSuite", run: runTestActivityAPIBatchUnpauseClientTestSuite},
	{Name: "TestActivityApiBatchUpdateOptionsClientTestSuite", run: runTestActivityAPIBatchUpdateOptionsClientTestSuite},
	{Name: "TestActivityApiPauseClientTestSuite", run: runTestActivityAPIPauseClientTestSuite},
	{Name: "TestActivityApiPause_AttributesToActivityInContextMetadata", run: runTestActivityAPIPauseAttributesToActivityInContextMetadata},
	{Name: "TestActivityApiResetClientTestSuite", run: runTestActivityAPIResetClientTestSuite},
	{Name: "TestActivityApiRulesClientTestSuite", run: runTestActivityAPIRulesClientTestSuite},
	{Name: "TestActivityApiUpdateClientTestSuite", run: runTestActivityAPIUpdateClientTestSuite},
	{Name: "TestActivityClientTestSuite", run: runTestActivityClientTestSuite},
	{Name: "TestActivityParityTestSuite", run: runTestActivityParityTestSuite},
	{Name: "TestActivityTestSuite", run: runTestActivityTestSuite},
	{Name: "TestActivityUpdateExecutionOptionsApi", run: runTestActivityUpdateExecutionOptionsAPI},
	{Name: "TestAddTasksSuite", run: runTestAddTasksSuite},
	{Name: "TestAdminBatchRefreshWorkflowTasksTestSuite", run: runTestAdminBatchRefreshWorkflowTasksTestSuite},
	{Name: "TestAdminRebuildMutableState_ChasmDisabled", run: runTestAdminRebuildMutableStateChasmDisabled},
	{Name: "TestAdminRebuildMutableState_ChasmEnabled", run: runTestAdminRebuildMutableStateChasmEnabled},
	{Name: "TestAdvancedVisibilitySuite", run: runTestAdvancedVisibilitySuite},
	{Name: "TestAdvancedVisibilitySuiteLegacy", run: runTestAdvancedVisibilitySuiteLegacy},
	{Name: "TestArchivalSuite", run: runTestArchivalSuite},
	{Name: "TestCallbacksMigrationSuite", run: runTestCallbacksMigrationSuite},
	{Name: "TestCallbacksSuiteCHASM", run: runTestCallbacksSuiteCHASM},
	{Name: "TestCallbacksSuiteHSM", run: runTestCallbacksSuiteHSM},
	{Name: "TestCancelWorkflowSuite", run: runTestCancelWorkflowSuite},
	{Name: "TestChasmSuite", run: runTestChasmSuite},
	{Name: "TestChildWorkflowSuite", run: runTestChildWorkflowSuite},
	{Name: "TestClientDataConverterTestSuite", run: runTestClientDataConverterTestSuite},
	{Name: "TestClientMiscTestSuite", run: runTestClientMiscTestSuite},
	{Name: "TestContinueAsNewTestSuite", run: runTestContinueAsNewTestSuite},
	{Name: "TestCronTestClientSuite", run: runTestCronTestClientSuite},
	{Name: "TestCronTestSuite", run: runTestCronTestSuite},
	{Name: "TestDLQSuite", run: runTestDLQSuite},
	{Name: "TestDeploymentVersionSuite", run: runTestDeploymentVersionSuite},
	{Name: "TestDescribeTestSuite", run: runTestDescribeTestSuite},
	{Name: "TestDispatchCancelToWorkerWithEagerActivity", run: runTestDispatchCancelToWorkerWithEagerActivity},
	{Name: "TestEagerWorkflowTestSuite", run: runTestEagerWorkflowTestSuite},
	{Name: "TestFairnessAutoEnableSuite", run: runTestFairnessAutoEnableSuite},
	{Name: "TestFairnessSuite", run: runTestFairnessSuite},
	{Name: "TestGetHistorySuite_DisableTransitionHistory", run: runTestGetHistorySuiteDisableTransitionHistory},
	{Name: "TestGetHistorySuite_EnableTransitionHistory", run: runTestGetHistorySuiteEnableTransitionHistory},
	{Name: "TestHistoryNodeCleanupSuite", run: runTestHistoryNodeCleanupSuite},
	{Name: "TestHttpApiTestSuite", run: runTestHTTPAPITestSuite},
	{Name: "TestLinksTestSuite", run: runTestLinksTestSuite},
	{Name: "TestMaxBufferedEventSuite", run: runTestMaxBufferedEventSuite},
	{Name: "TestMirroredIncludeExcludeSpec", run: runTestMirroredIncludeExcludeSpec},
	{Name: "TestMirroredIncludeExcludeSpecOnUpdate", run: runTestMirroredIncludeExcludeSpecOnUpdate},
	{Name: "TestNamespaceInterceptorTestSuite", run: runTestNamespaceInterceptorTestSuite},
	{Name: "TestNamespaceSuite", run: runTestNamespaceSuite},
	{Name: "TestNexusAPIValidationTestSuite", run: runTestNexusAPIValidationTestSuite},
	{Name: "TestNexusApiTestSuiteWithLegacyErrorPaths", run: runTestNexusAPITestSuiteWithLegacyErrorPaths},
	{Name: "TestNexusApiTestSuiteWithTemporalFailures", run: runTestNexusAPITestSuiteWithTemporalFailures},
	{Name: "TestNexusEndpointsCommonSuite", run: runTestNexusEndpointsCommonSuite},
	{Name: "TestNexusEndpointsMatchingSuite", run: runTestNexusEndpointsMatchingSuite},
	{Name: "TestNexusEndpointsOperatorSuite", run: runTestNexusEndpointsOperatorSuite},
	{Name: "TestNexusMatchingTestSuite", run: runTestNexusMatchingTestSuite},
	{Name: "TestNexusStandaloneTestSuite", run: runTestNexusStandaloneTestSuite},
	{Name: "TestNexusWorkflowTestSuiteCHASM", run: runTestNexusWorkflowTestSuiteCHASM},
	{Name: "TestNexusWorkflowTestSuiteHSM", run: runTestNexusWorkflowTestSuiteHSM},
	{Name: "TestNexusWorkflowUpdateTestSuite", run: runTestNexusWorkflowUpdateTestSuite},
	{Name: "TestNilSearchAttributeSuite", run: runTestNilSearchAttributeSuite},
	{Name: "TestPartitionScaling_Backlog", run: runTestPartitionScalingBacklog},
	{Name: "TestPartitionScaling_Down", run: runTestPartitionScalingDown},
	{Name: "TestPartitionScaling_Down_AndStopPolling", run: runTestPartitionScalingDownAndStopPolling},
	{Name: "TestPartitionScaling_Down_FromDC", run: runTestPartitionScalingDownFromDC},
	{Name: "TestPartitionScaling_Up", run: runTestPartitionScalingUp},
	{Name: "TestPartitionScaling_Up_FromDC", run: runTestPartitionScalingUpFromDC},
	{Name: "TestPauseWorkflowExecutionSuite", run: runTestPauseWorkflowExecutionSuite},
	{Name: "TestPollerScalingFunctionalSuite", run: runTestPollerScalingFunctionalSuite},
	{Name: "TestPrematureEosTestSuite", run: runTestPrematureEosTestSuite},
	{Name: "TestPrioritySuite", run: runTestPrioritySuite},
	{Name: "TestPurgeDLQTasksSuite", run: runTestPurgeDLQTasksSuite},
	{Name: "TestQueryWorkflowSuite", run: runTestQueryWorkflowSuite},
	{Name: "TestRawHistorySuite", run: runTestRawHistorySuite},
	{Name: "TestRelayTaskTestSuite", run: runTestRelayTaskTestSuite},
	{Name: "TestResetWorkflowTestSuite", run: runTestResetWorkflowTestSuite},
	{Name: "TestScheduleCHASM", run: runTestScheduleCHASM},
	{Name: "TestScheduleCHASMWorkflowPauseInteraction", run: runTestScheduleCHASMWorkflowPauseInteraction},
	{Name: "TestScheduleCountsVisibility", run: runTestScheduleCountsVisibility},
	{Name: "TestScheduleCreationRolloutPercent", run: runTestScheduleCreationRolloutPercent},
	{Name: "TestScheduleFarFutureActionTimes", run: runTestScheduleFarFutureActionTimes},
	{Name: "TestScheduleManyCalendars", run: runTestScheduleManyCalendars},
	{Name: "TestScheduleMigrationDeferredWithRunningWorkflow", run: runTestScheduleMigrationDeferredWithRunningWorkflow},
	{Name: "TestScheduleMigrationTestSuite", run: runTestScheduleMigrationTestSuite},
	{Name: "TestScheduleMigrationV1ToV2NoDuplicateRecentActions", run: runTestScheduleMigrationV1ToV2NoDuplicateRecentActions},
	{Name: "TestScheduleMigration_NoRunningWorkflows_GeneratorStarts", run: runTestScheduleMigrationNoRunningWorkflowsGeneratorStarts},
	{Name: "TestScheduleMigration_StaleRunningDoesNotSkipPending", run: runTestScheduleMigrationStaleRunningDoesNotSkipPending},
	{Name: "TestScheduleNextActionTimeVisibility", run: runTestScheduleNextActionTimeVisibility},
	{Name: "TestScheduleV1", run: runTestScheduleV1},
	{Name: "TestScheduleV1WorkflowPauseInteraction", run: runTestScheduleV1WorkflowPauseInteraction},
	{Name: "TestSignalWithStartFromWorkflowTestSuite", run: runTestSignalWithStartFromWorkflowTestSuite},
	{Name: "TestSignalWorkflowTestSuiteChasm", run: runTestSignalWorkflowTestSuiteChasm},
	{Name: "TestSignalWorkflowTestSuiteLegacy", run: runTestSignalWorkflowTestSuiteLegacy},
	{Name: "TestSizeLimitFunctionalSuite", run: runTestSizeLimitFunctionalSuite},
	{Name: "TestStandaloneActivityTestSuite", run: runTestStandaloneActivityTestSuite},
	{Name: "TestStickyTqTestSuite", run: runTestStickyTqTestSuite},
	{Name: "TestTLSFunctionalSuite", run: runTestTLSFunctionalSuite},
	{Name: "TestTaskQueueStats_Pri_Suite", run: runTestTaskQueueStatsPriSuite},
	{Name: "TestTaskQueueSuite", run: runTestTaskQueueSuite},
	{Name: "TestTimeSkippingFastForwardFunctionalSuite", run: runTestTimeSkippingFastForwardFunctionalSuite},
	{Name: "TestTimeSkippingPropagationTestSuite", run: runTestTimeSkippingPropagationTestSuite},
	{Name: "TestTimeSkippingTestSuite", run: runTestTimeSkippingTestSuite},
	{Name: "TestTransientTaskSuite", run: runTestTransientTaskSuite},
	{Name: "TestUpdateWithStartSuite", run: runTestUpdateWithStartSuite},
	{Name: "TestUpdateWorkflowSdkSuite", run: runTestUpdateWorkflowSdkSuite},
	{Name: "TestUserMetadataSuite", run: runTestUserMetadataSuite},
	{Name: "TestUserTimersTestSuite", run: runTestUserTimersTestSuite},
	{Name: "TestVersioning3FunctionalSuite", run: runTestVersioning3FunctionalSuite},
	{Name: "TestVersioning3OneTimeOverrideFunctionalSuite", run: runTestVersioning3OneTimeOverrideFunctionalSuite},
	{Name: "TestVersioningFunctionalSuite", run: runTestVersioningFunctionalSuite},
	{Name: "TestWFTFailureReportedProblemsTestSuite", run: runTestWFTFailureReportedProblemsTestSuite},
	{Name: "TestWorkerCommandsTaskSuite", run: runTestWorkerCommandsTaskSuite},
	{Name: "TestWorkerDeploymentSuite", run: runTestWorkerDeploymentSuite},
	{Name: "TestWorkerRegistryTestSuite", run: runTestWorkerRegistryTestSuite},
	{Name: "TestWorkflowAPIBatchCancelClientTestSuite", run: runTestWorkflowAPIBatchCancelClientTestSuite},
	{Name: "TestWorkflowAPIBatchDeleteClientTestSuite", run: runTestWorkflowAPIBatchDeleteClientTestSuite},
	{Name: "TestWorkflowAPIBatchResetClientTestSuite", run: runTestWorkflowAPIBatchResetClientTestSuite},
	{Name: "TestWorkflowAPIBatchSignalClientTestSuite", run: runTestWorkflowAPIBatchSignalClientTestSuite},
	{Name: "TestWorkflowAPIBatchTerminateClientTestSuite", run: runTestWorkflowAPIBatchTerminateClientTestSuite},
	{Name: "TestWorkflowAPIBatchUpdateOptionsClientTestSuite", run: runTestWorkflowAPIBatchUpdateOptionsClientTestSuite},
	{Name: "TestWorkflowAliasSearchAttributeTestSuite", run: runTestWorkflowAliasSearchAttributeTestSuite},
	{Name: "TestWorkflowBufferedEventsTestSuite", run: runTestWorkflowBufferedEventsTestSuite},
	{Name: "TestWorkflowCompletionPaginationTestSuite", run: runTestWorkflowCompletionPaginationTestSuite},
	{Name: "TestWorkflowDeleteExecutionSuite", run: runTestWorkflowDeleteExecutionSuite},
	{Name: "TestWorkflowFailuresTestSuite", run: runTestWorkflowFailuresTestSuite},
	{Name: "TestWorkflowMemoTestSuite", run: runTestWorkflowMemoTestSuite},
	{Name: "TestWorkflowResetTestSuite", run: runTestWorkflowResetTestSuite},
	{Name: "TestWorkflowResetWithChildTestSuite", run: runTestWorkflowResetWithChildTestSuite},
	{Name: "TestWorkflowTaskTestSuite", run: runTestWorkflowTaskTestSuite},
	{Name: "TestWorkflowTestSuite", run: runTestWorkflowTestSuite},
	{Name: "TestWorkflowTimerTestSuite", run: runTestWorkflowTimerTestSuite},
	{Name: "TestWorkflowTypeEncodingSuite", run: runTestWorkflowTypeEncodingSuite},
	{Name: "TestWorkflowUpdateSuite", run: runTestWorkflowUpdateSuite},
	{Name: "TestWorkflowVisibilityTestSuite", run: runTestWorkflowVisibilityTestSuite},
}

// FunctionalTestEntries returns the root functional-test inventory in stable
// lexical order. The returned slice can be modified by the caller.
func FunctionalTestEntries() []FunctionalTestEntry {
	return append([]FunctionalTestEntry(nil), functionalTestEntries...)
}
