# https://d2lang.com
# Generate SVG by running `make` inside of `docs/`.

vars: {
  d2-config: {
    layout-engine: dagre
  }
}

*.style.bold: true

ComponentRef: {
    grid-rows: 4
    ExecutionKey
    ComponentPath
    "initial VersionedTransition"
    "lastUpdate VersionedTransition"
}
