# https://d2lang.com
# Generate SVG by running `make` inside of `docs/`.

vars: {
  d2-config: {
    layout-engine: dagre
  }
}

*.style.bold: true

Component -> "Search Attributes": "updates in Apply Logic"
"Search Attributes" -> Visibility: "indexed in"
