# https://d2lang.com
# Generate SVG by running `make` inside of `docs/`.

vars: {
  d2-config: {
    layout-engine: dagre
  }
}

*.style.font-size: 18
*.style.bold: true

"Component Type": {
    grid-rows: 4
    "Field[T]"
    "Map[K, T]"
    ParentPtr
    Transient
}
