# https://d2lang.com
# Generate SVG by running `make` inside of `docs/`.

vars: {
  d2-config: {
    layout-engine: elk
  }
}

*.style.bold: true

Node: {
    grid-rows: 5
    Name
    Component
    "initial VersionedTransition"
    "lastUpdate VersionedTransition"
    "Children (0..n Node)"
}
