# https://d2lang.com
# Generate SVG by running `make` inside of `docs/`.

vars: {
  d2-config: {
    layout-engine: dagre
  }
}

*.style.bold: true

VersionedTransition: {
    grid-rows: 2
    FailoverVersion
    TransitionCount
}
