# https://d2lang.com
# Generate SVG by running `make` inside of `docs/`.

vars: {
  d2-config: {
    layout-engine: tala
  }
}

Cluster: {
    label: "Temporal Cluster"
    style.fill: transparent
    style.stroke-dash: 3
    style.double-border: false

    Server: {
        style.fill: transparent
        style.stroke-dash: 3

        History: {
            style.multiple: true
        }
        Matching: {
            style.multiple: true
        }
        Frontend: {
            style.multiple: true
        }
    }
    Database: {
        style.border-radius: 100
    }
}

Worker: {
    style.multiple: true
}

Worker -> Cluster.Server.Frontend: Poll Tasks
Cluster.Server.Frontend -> Cluster.Server.Matching: Poll Tasks
Cluster.Server.History <-> Cluster.Server.Matching: Add Tasks \n Record Start
Cluster.Server.Matching <-> Cluster.Database
