# https://d2lang.com
# Generate SVG by running `make` inside of `docs/`.

history_node: {
    shape: sql_table
    tree_id: uuid { constraint: [PartitionKey, PK] }
    branch_id: uuid { constraint: PK }
    node_id: bigint { constraint: PK }
    txn_id: bigint { constraint: PK }
    prev_txn_id: bigint
    data: blob
}
