// The MIT License
//
// Copyright (c) 2020 Temporal Technologies Inc.  All rights reserved.
//
// Copyright (c) 2020 Uber Technologies, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// Code generated by MockGen. DO NOT EDIT.
// Source: event_cache.go

// Package definition is a generated GoMock package.
package definition

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "go.temporal.io/api/history/v1"
)

// MockEventCache is a mock of EventCache interface.
type MockEventCache struct {
	ctrl     *gomock.Controller
	recorder *MockEventCacheMockRecorder
}

// MockEventCacheMockRecorder is the mock recorder for MockEventCache.
type MockEventCacheMockRecorder struct {
	mock *MockEventCache
}

// NewMockEventCache creates a new mock instance.
func NewMockEventCache(ctrl *gomock.Controller) *MockEventCache {
	mock := &MockEventCache{ctrl: ctrl}
	mock.recorder = &MockEventCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventCache) EXPECT() *MockEventCacheMockRecorder {
	return m.recorder
}

// DeleteEvent mocks base method.
func (m *MockEventCache) DeleteEvent(key EventKey) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteEvent", key)
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockEventCacheMockRecorder) DeleteEvent(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockEventCache)(nil).DeleteEvent), key)
}

// GetEvent mocks base method.
func (m *MockEventCache) GetEvent(ctx context.Context, key EventKey, firstEventID int64, branchToken []byte) (*v1.HistoryEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, key, firstEventID, branchToken)
	ret0, _ := ret[0].(*v1.HistoryEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockEventCacheMockRecorder) GetEvent(ctx, key, firstEventID, branchToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockEventCache)(nil).GetEvent), ctx, key, firstEventID, branchToken)
}

// PutEvent mocks base method.
func (m *MockEventCache) PutEvent(key EventKey, event *v1.HistoryEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PutEvent", key, event)
}

// PutEvent indicates an expected call of PutEvent.
func (mr *MockEventCacheMockRecorder) PutEvent(key, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutEvent", reflect.TypeOf((*MockEventCache)(nil).PutEvent), key, event)
}
