steps:
    - label: ":golang: unit test"
      agents:
        queue: "default"
        docker: "*"
      command: "make cover_profile"
      artifact_paths:
        - "build/coverage/*.out"
      plugins:
        - docker-compose#v3.0.0:
            run: unit-test
            args:
              - SSH_PRIVATE_KEY: "$(cat private_ssh_key)"
            config: docker/buildkite/docker-compose.yml