steps:
    - label: ":golang: unit test"
      agents:
        queue: "default"
        docker: "*"
      command: "make cover_profile"
      artifact_paths:
        - "build/coverage/*.out"
      plugins:
        - docker-compose#v3.0.3:
            run: unit-test
            config: docker/buildkite/docker-compose.yml
            volumes:
              - "${SSH_AUTH_SOCK}:/ssh-agent"
              - "${HOME}/.ssh/known_hosts:/root/.ssh/known_hosts"
            environment:
              - SSH_AUTH_SOCK=/ssh-agent
              - GOPRIVATE=go.temporal.io/temporal