steps:
    - label: ":golang: unit test"
      agents:
        queue: "workers"
        docker: "*"
      command: "make cover_profile"
      artifact_paths:
        - "build/coverage/*.out"
      plugins:
        - docker-compose#v3.0.0:
            run: unit-test
            config: docker/buildkite/docker-compose.yml