steps:
  - label: ":golang: unit test"
    agents:
      queue: "default"
      docker: "*"
    command: "make cover_profile"
    artifact_paths:
      - "build/coverage/*.out"
    plugins:
      - docker-compose#v3.1.0:
          run: unit-test
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration test with cassandra"
    agents:
      queue: "default"
      docker: "*"
    command: "make cover_integration_profile"
    artifact_paths:
      - "build/coverage/*.out"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.1.0:
          run: integration-test-cassandra
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration xdc test with cassandra"
    agents:
      queue: "default"
      docker: "*"
    command: "make cover_xdc_profile"
    artifact_paths:
      - "build/coverage/*.out"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.1.0:
          run: integration-test-xdc-cassandra
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration ndc test with cassandra"
    agents:
      queue: "default"
      docker: "*"
    command: "make cover_ndc_profile"
    artifact_paths:
      - "build/coverage/*.out"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.1.0:
          run: integration-test-xdc-cassandra
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration test with mysql"
    agents:
      queue: "default"
      docker: "*"
    command: "make cover_integration_profile"
    artifact_paths:
      - "build/coverage/*.out"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.1.0:
          run: integration-test-mysql
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration xdc test with mysql"
    agents:
      queue: "default"
      docker: "*"
    command: "make cover_xdc_profile"
    artifact_paths:
      - "build/coverage/*.out"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.1.0:
          run: integration-test-xdc-mysql
          config: docker/buildkite/docker-compose.yml

  - label: ":golang: integration ndc test with mysql"
    agents:
      queue: "default"
      docker: "*"
    command: "make cover_ndc_profile"
    artifact_paths:
      - "build/coverage/*.out"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-compose#v3.1.0:
          run: integration-test-xdc-mysql
          config: docker/buildkite/docker-compose.yml

  - wait

  - label: ":golang: code-coverage"
    agents:
      queue: "default"
      docker: "*"
    command: "scripts/buildkite/gocov.sh"
    retry:
      automatic:
        limit: 2
    plugins:
      - docker-compose#v3.1.0:
          run: coverage-report
          config: docker/buildkite/docker-compose.yml

  - label: ":docker: build and push master"
    agents:
      queue: "default"
      docker: "*"
    command: "scripts/buildkite/docker-push.sh"
    retry:
      automatic:
        limit: 1
    plugins:
      - docker-login#v2.0.1:
          username: temporaltech
          password-env: DOCKER_LOGIN_PASSWORD