# Include this file to run Prometheus as one more dependency:
# docker-compose -f docker-compose.yml -f docker-compose.linux.yml -f docker-compose.prometheus.yml up

version: "3.5"

services:
  # Use http://localhost:9090/ to access Prometheus.
  prometheus:
    image: prom/prometheus
    container_name: temporal-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    # Linux
    network_mode: host
    # darwin/Windows
#    ports:
#      - "9090:9090"
#    networks:
#      - temporal-dependencies-network

  # Use http://localhost:3000/ to access Grafana (admin/admin).
  grafana:
    image: grafana/grafana
    container_name: temporal-grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    # Linux
    network_mode: host
    # darwin/Windows
#    ports:
#      - "3000:3000"
#    networks:
#      - temporal-dependencies-network
