# Include this file to run Jaeger as one more dependency:
# docker-compose -f docker-compose.yml -f docker-compose.linux.yml -f docker-compose.jaeger.yml up
version: "3.5"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: temporal-jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - temporal-dependencies-network
