name: Upload Artifact with Retry
description: Upload an artifact with retries for transient service failures
inputs:
  name:
    description: Artifact name
    required: true
  path:
    description: Files to upload
    required: true
  if-no-files-found:
    description: Behavior when no files match the path
    required: false
    default: warn
  include-hidden-files:
    description: Whether to include hidden files
    required: false
    default: "false"
  retention-days:
    description: Number of days to retain the artifact
    required: true
runs:
  using: composite
  steps:
    - name: Upload artifact
      id: upload
      # Can't pin to major because the action linter doesn't recognize the include-hidden-files flag.
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      continue-on-error: true
      with: &artifact-inputs
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        if-no-files-found: ${{ inputs['if-no-files-found'] }}
        include-hidden-files: ${{ inputs['include-hidden-files'] }}
        retention-days: ${{ inputs['retention-days'] }}
        overwrite: true

    - name: Wait before retrying artifact upload
      if: ${{ !cancelled() && steps.upload.outcome == 'failure' }}
      shell: bash
      run: sleep 5

    - name: Retry artifact upload
      id: retry
      if: ${{ !cancelled() && steps.upload.outcome == 'failure' }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      continue-on-error: true
      with: *artifact-inputs

    - name: Wait before retrying artifact upload again
      if: ${{ !cancelled() && steps.retry.outcome == 'failure' }}
      shell: bash
      run: sleep 15

    - name: Retry artifact upload again
      if: ${{ !cancelled() && steps.retry.outcome == 'failure' }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with: *artifact-inputs
