steps:
  - label: ":golang: build"
    agents:
      queue: "default"
      docker: "*"
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          build: build
          build-alias:
            # All services in the docker-compose file that run the server or tests should be listed here:
            - "db-integration-test"
            - "integration-test-cassandra"
            - "integration-test-cassandra-es8"
            - "integration-test-cassandra-opensearch"
            - "integration-test-mysql"
            - "integration-test-mysql8"
            - "integration-test-postgresql"
            - "integration-test-postgresql12"
            - "integration-test-sqlite"
            - "integration-test-xdc-cassandra"
            - "integration-test-xdc-mysql"
            - "integration-test-xdc-mysql8"
            - "integration-test-xdc-postgresql"
            - "integration-test-xdc-postgresql12"
            - "coverage-report"
          config: ./develop/buildkite/docker-compose.yml
          image-repository: "283266070392.dkr.ecr.us-west-2.amazonaws.com/buildkite"

  - wait

  - label: ":golang: misc checks"
    agents:
      queue: "default"
      docker: "*"
    command: "make ci-build-misc"
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: build
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: unit test"
    agents:
      queue: "default"
      docker: "*"
    command: "make unit-test-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: build
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: integration test"
    agents:
      queue: "default"
      docker: "*"
    command: "make integration-test-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: db-integration-test
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional test with cassandra"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-coverage"
    parallelism: 3
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-cassandra
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional test with cassandra (ES8)"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-coverage"
    parallelism: 3
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-cassandra-es8
          config: ./develop/buildkite/docker-compose.yml

  # TODO(rodrigozhou): olivere client is incompatible with OpenSearch PIT
  # - label: ":golang: functional test with cassandra (OpenSearch 2)"
  #   agents:
  #     queue: "default"
  #     docker: "*"
  #   command: "make functional-test-coverage"
  #   artifact_paths:
  #     - ".coverage/*.out"
  #   retry:
  #     automatic:
  #       limit: 1
  #   plugins:
  #     - ecr#v2.7.0: {login: true}
  #     - docker-compose#v4.14.0:
  #         run: integration-test-cassandra-opensearch
  #         config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional xdc test with cassandra"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-xdc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-cassandra
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional ndc test with cassandra"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-ndc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-cassandra
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional test with mysql"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-coverage"
    parallelism: 3
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-mysql
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional xdc test with mysql"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-xdc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-mysql
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional ndc test with mysql"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-ndc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-mysql
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional test with mysql 8"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-coverage"
    parallelism: 3
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-mysql8
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional xdc test with mysql 8"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-xdc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-mysql8
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional ndc test with mysql 8"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-ndc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-mysql8
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional test with postgresql"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-coverage"
    parallelism: 3
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-postgresql
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional xdc test with postgresql"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-xdc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-postgresql
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional ndc test with postgresql"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-ndc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-postgresql
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional test with postgresql pgx"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-postgresql-pgx
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional xdc test with postgresql pgx"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-xdc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-postgresql-pgx
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional ndc test with postgresql pgx"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-ndc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-postgresql-pgx
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional test with postgresql 12"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-coverage"
    parallelism: 3
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-postgresql12
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional xdc test with postgresql 12"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-xdc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-postgresql12
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional ndc test with postgresql 12"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-ndc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-postgresql12
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional test with postgresql 12 pgx"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-coverage"
    parallelism: 3
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
<<<<<<< HEAD
      - docker-compose#v4.14.0:
          run: integration-test-postgresql12-pgx
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional xdc test with postgresql 12 pgx"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-xdc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-postgresql12-pgx
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional ndc test with postgresql 12 pgx"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-ndc-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-xdc-postgresql12-pgx
          config: ./develop/buildkite/docker-compose.yml

  - label: ":golang: functional test with sqlite"
    agents:
      queue: "default"
      docker: "*"
    command: "make functional-test-coverage"
    artifact_paths:
      - ".coverage/*.out"
      - ".testreport/*.xml"
    retry:
      automatic:
        limit: 1
    plugins:
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: integration-test-sqlite
          config: ./develop/buildkite/docker-compose.yml

  - wait: ~
    continue_on_failure: true  # required for test reports of failed build to be picked up
  
  - label: ":mag: test-report"
    agents:
      queue: "default"
      docker: "*"
    retry:
      automatic:
        limit: 2
    plugins:
      - test-collector#v1.10.0:
          files: ".testreport/*.xml"
          format: junit

  - label: ":coverage: coverage-report"
    agents:
      queue: "default"
      docker: "*"
    command: "make ci-coverage-report"
    artifact_paths:
      - ".coverage/summary.out"
      - ".coverage/summary.out.html"
    retry:
      automatic:
        limit: 2
    plugins:
      - artifacts#v1.9.0:
          download:
            - ".coverage/*.out"
      - ecr#v2.7.0: {login: true}
      - docker-compose#v4.14.0:
          run: coverage-report
          config: ./develop/buildkite/docker-compose.yml
