# Overrides for Mac/Darwin users.
services:
  prometheus:
    volumes:
      - ./prometheus-darwin:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - temporal-dev-network
  grafana:
    ports:
      - "3000:3000"
    networks:
      - temporal-dev-network
  tempo:
    depends_on:
      - grafana
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
    networks:
      - temporal-dev-network
  temporal-ui:
    environment:
      - TEMPORAL_ADDRESS=host.docker.internal:7233
    ports:
      - "8080:8080"
    networks:
      - temporal-dev-network
