name: Build Docker Images
description: |
  Build Temporal Docker images from binaries.

  Prerequisites:
    - The build-binaries action must run before this action to produce the binaries.

inputs:
  push:
    description: "Push images to Docker Hub"
    required: false
    default: "false"
  tag-latest:
    description: "Tag images as latest"
    required: false
    default: "false"
  platform:
    description: "Single platform to build (e.g., linux/amd64)"
    required: false
    default: ""
  load:
    description: "Load image into local Docker daemon (only works with linux/amd64 - the runner architecture)"
    required: false
    default: "false"
  dockerhub-username:
    description: "Docker Hub username"
    required: false
  dockerhub-token:
    description: "Docker Hub token"
    required: false

runs:
  using: composite
  steps:
    - name: Build docker-build-helper
      shell: bash
      working-directory: ${{ github.workspace }}/.github/actions/build-docker-images/scripts
      run: |
        go build -o docker-build-helper .

    - name: Validate and sanitize branch name for Docker tag
      id: sanitize-tag
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        .github/actions/build-docker-images/scripts/docker-build-helper sanitize-tag

    - name: Organize binaries for Docker
      id: organize-binaries
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        PLATFORM: ${{ inputs.platform }}
      run: |
        .github/actions/build-docker-images/scripts/docker-build-helper organize-binaries

    - name: Download Temporal CLI
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        AVAILABLE_ARCHS: ${{ steps.organize-binaries.outputs.available-archs }}
      run: |
        .github/actions/build-docker-images/scripts/docker-build-helper download-cli

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: inputs.push == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Build Docker images
      if: inputs.push != 'true'
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        IMAGE_REPO: temporaliotest
        IMAGE_SHA_TAG: ${{ github.sha }}
        IMAGE_BRANCH_TAG: ${{ steps.sanitize-tag.outputs.tag }}
        TEMPORAL_SHA: ${{ github.sha }}
        TAG_LATEST: ${{ inputs.tag-latest }}
      run: |
        if [ -n "${{ inputs.platform }}" ]; then
          docker buildx bake \
            --set "*.platform=${{ inputs.platform }}" \
            ${{ inputs.load == 'true' && '--load' || '' }} \
            -f docker/docker-bake.hcl \
            server admin-tools
        else
          docker buildx bake \
            ${{ inputs.load == 'true' && '--load' || '' }} \
            -f docker/docker-bake.hcl \
            server admin-tools
        fi

    - name: Verify admin-tools binaries
      if: inputs.push != 'true' && inputs.load == 'true'
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        IMAGE_REPO: temporaliotest
        IMAGE_SHA_TAG: ${{ github.sha }}
      run: |
        echo "Verifying admin-tools binaries are present in the image..."
        MISSING_TOOLS=""

        for tool in temporal temporal-server temporal-cassandra-tool temporal-sql-tool temporal-elasticsearch-tool tdbg; do
          if docker run --rm "${IMAGE_REPO}/admin-tools:${IMAGE_SHA_TAG}" sh -c "[ -x /usr/local/bin/${tool} ]"; then
            echo "✓ ${tool} found and executable"
          else
            echo "✗ ${tool} is missing or not executable"
            MISSING_TOOLS="${MISSING_TOOLS} ${tool}"
          fi
        done

        if [ -n "${MISSING_TOOLS}" ]; then
          echo "ERROR: The following tools are missing or not executable:${MISSING_TOOLS}"
          exit 1
        fi

        echo "All admin tools verified successfully"

    - name: Build and push Docker images
      if: inputs.push == 'true'
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        IMAGE_REPO: temporaliotest
        IMAGE_SHA_TAG: ${{ github.sha }}
        IMAGE_BRANCH_TAG: ${{ steps.sanitize-tag.outputs.tag }}
        TEMPORAL_SHA: ${{ github.sha }}
        TAG_LATEST: ${{ inputs.tag-latest }}
      run: |
        docker buildx bake \
          --push \
          -f docker/docker-bake.hcl \
          server admin-tools
