syntax = "proto3";

package temporal.server.chasm.lib.flowcontrol.proto.v1;

import "google/protobuf/timestamp.proto";
// import "temporal/api/taskqueue/v1/message.proto";
import "temporal/server/api/common/v1/api_category.proto";
import "temporal/server/api/routing/v1/extension.proto";

option go_package = "go.temporal.io/server/chasm/lib/flowcontrol/gen/fcpb;fcpb";

// FIXME: before merging, replace this with temporal.api.taskqueue.v1.ConcurrencyLimit
message ConcurrencyLimit {
    // Maximum number of concurrent tasks that may be running at a time across the whole task
    // queue. Note that in situations like network partitions, the server's idea of what is
    // running on workers may be out of date, and this limit could be exceeded from the point
    // of view of workers.
    int32 concurrent_tasks = 1;
}

message ConcurrencyState {
  // Limit for concurrent slots.
  // temporal.api.taskqueue.v1.ConcurrencyLimit config = 1;
  ConcurrencyLimit config = 1;
  // Incrementing version for config, to avoid flipping to an older config. For limits set from
  // task queue config, this is the user data version. For limits set from API, this is its own
  // independent version.
  int64 config_version = 2;

  // Slots reserved or committed. Entries should be unique by slot_id. Length is bounded by
  // config.ConcurrentTasks.
  repeated Slot slots = 3;

  // Generation is used to ensure Wait is monotonic. See comment in Wait for details.
  int64 generation = 4;
  // WakeUpTo is used to select and stage wakeups by priority.
  int64 wake_up_to = 5;
  // WakeAll means wake up to maximum priority.
  bool wake_all = 6;
  // WakeStage is the number of staged wakeups we've done since the first one.
  int32 wake_stage = 7;

  message Slot {
    // Identifier generated by the caller for this slot.
    string slot_id = 1;
    // Whether slot is committed or only reserved. Reserved slots must have an expiry time.
    // Committed slots don't expire, they must be Released.
    bool committed = 2;
    // Expiry time for reserved slot.
    google.protobuf.Timestamp expires = 3;
  }
}

message ConcurrencyBatchRequest {
  string namespace_id = 1;
  string key = 2;

  // Reserve reserves a slot for a limited time. Succeeds if the slot is newly reserved or
  // already reserved _or already committed_ for the task, i.e. idempotent. May not be durable:
  // a successful Reserve followed by a Commit may not succeed even within the timeout. Callers
  // must handle that situation correctly.
  repeated string reserve_slots = 3;
  // CancelReservation cancels a reservation early. Note that committed slots cannot be
  // canceled, they must be Released. Idempotent. May not be durable.
  repeated string cancel_reservation_slots = 4;
  // Commit promotes a reservation to a committed slot. Succeeds if the reservation was
  // promoted, or was already committed, i.e. idempotent. Durable.
  repeated string commit_slots = 5;
  // Release frees a comitted slot. Succeeds if the committed slot was released or if there was
  // no committed slot, i.e. idempotent. Durable.
  repeated string release_slots = 6;

  // For whole-task-queue limits, the initial limit and updates to the limit come through task
  // queue config, so we need to pass them to the chasm object. We just do it on every call.
  // temporal.api.taskqueue.v1.ConcurrencyLimit config_update = 7;
  ConcurrencyLimit config_update = 7;
  int64 config_update_version = 8;
}

message ConcurrencyBatchResponse {
  // Generation of limiter state.
  int64 generation = 1;

  repeated bool reserve_success = 2;
  // Note: we don't need a cancel_success, it's always considered successful.
  repeated bool commit_success = 3;
  // Note: we don't need a release_success, it's always considered successful.
}

message ConcurrencyWaitRequest {
  string namespace_id = 1;
  string key = 2;
  // Generation is used to ensure monotonicity of waits. The caller should pass its last known
  // generation. If it's out of date, the server may retry internally with the current
  // generation, and return a newer one. Before context timeout, the server should return
  // success with zero wake_tokens and the current generation.
  int64 generation = 3;
  // WakePriority is used to order waiters. It should be a value that is meaningful at
  // namespace scope, and is usually different for different tasks. Currently we use a
  // combination of task priority and create time.
  int64 wake_priority = 4;
  // How many queues are known to be waiting for this limiter. The server may take this into
  // account when staging wakes. If this is missing, 1 is assumed.
  int32 requested_wake_tokens = 5;
}

message ConcurrencyWaitResponse {
  // Generation of limiter state.
  int64 generation = 1;
  // Number of slots that the client should consider available. This may be zero when the call
  // timed out without slots available. It may be less than requested_tokens if there aren't
  // enough available. It may also be less than the number of slots available, if the limiter
  // wants to divide available slots among multiple waiters.
  int32 wake_tokens = 2;
}

service ConcurrencyService {
  // Batch applies a batch of operations to one limiter.
  //
  // Note that matching calls Reserve, CancelReservation, and Commit, and history calls
  // Release, so no single batch should ever contain Release mixed with anything else, but
  // they're combined in one RPC definition for simplicity.
  //
  // All slot ids in one batch should be distinct; it's not possible to Reserve and Commit the
  // same slot at once. However, the server is not required to flag this as an error.
  //
  // Reserve and CancelReservation may not be durable, while Commit and Release must be
  // durable. The server may or may not split the batch into multiple CHASM transitions with
  // different durability, so callers should not assume that e.g. a Reserve plus Commit in one
  // batch means that the Reserve was durable.
  rpc Batch(ConcurrencyBatchRequest) returns (ConcurrencyBatchResponse) {
    option (temporal.server.api.routing.v1.routing).business_id = "key";
    option (temporal.server.api.common.v1.api_category).category = API_CATEGORY_STANDARD;
  };

  // Wait is a long-poll RPC that returns when at least one slot is free, or timeout.
  rpc Wait(ConcurrencyWaitRequest) returns (ConcurrencyWaitResponse) {
    option (temporal.server.api.routing.v1.routing).business_id = "key";
    option (temporal.server.api.common.v1.api_category).category = API_CATEGORY_LONG_POLL;
  };
}
