syntax = "proto3";

package temporal.server.api.persistence.v1;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "temporal/api/common/v1/message.proto";
import "temporal/api/enums/v1/workflow.proto";

option go_package = "go.temporal.io/server/api/persistence/v1;persistence";

message VisibilityExecutionInfo {
  // Namespace ID.
  string namespace_id = 1;
  // Namespace name. It may be empty if the namespace was deleted and this
  // record is still in Visibility.
  string namespace = 2;
  // Workflow execution (workflow ID and run ID).
  temporal.api.common.v1.WorkflowExecution execution = 3;
  // Workflow type name.
  temporal.api.common.v1.WorkflowType workflow_type = 4;
  // Workflow execution status.
  temporal.api.enums.v1.WorkflowExecutionStatus status = 5;
  // Start time.
  google.protobuf.Timestamp start_time = 6;
  // Close time. It is nil if workflow is still running.
  google.protobuf.Timestamp close_time = 7;
  // Duration. It is nil if workflow is still running.
  google.protobuf.Duration execution_duration = 8;
  // History length. It is 0 if workflow is still running.
  int64 history_length = 9;
  // History size bytes. It is 0 if workflow is still running.
  int64 history_size_bytes = 10;
  // State transition count. It is 0 if workflow is still running.
  int64 state_transition_count = 11;
}
