# https://d2lang.com
# Generate SVG by running `make` inside of `docs/`.

TaskQueueFoo: {
    label: "task queue 'foo'"
    style.stroke-dash: 3
    style.fill: transparent

    Partitions: {
        label: ""
        style.fill: transparent
        style.stroke: transparent

        Root: {
            label: "foo"
        }
        1: {
            label: "/_sys/foo/1"
        }
        2: {
            label: "/_sys/foo/2"
        }
        3: {
            label: "/_sys/foo/3"
        }

        Root <- 1
        Root <- 2
        Root <- 3
    }
}