name: PR Placeholder Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-placeholders:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - name: Check for underscore placeholders
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: prNumber
            });

            const body = pr.data.body || '';
            const lines = body.split('\n');
            const placeholderLines = lines.filter(line => {
              const trimmed = line.trim();
              return /^_.*_$/.test(trimmed);
            });

            if (placeholderLines.length > 0) {
              core.notice(
                `⚠️ Found ${placeholderLines.length} placeholder line(s) in PR description:\n` +
                placeholderLines.map(l => `- ${l.trim()}`).join('\n') +
                `\nPlease replace or remove them before merging.`
              );
            } else {
              console.log("✅ No placeholder lines detected.");
            }
