name: Release

on:
  release:
    types:
      - released

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Build binaries
        uses: ./.github/actions/build-binaries
        with:
          snapshot: false
          release: true
