name: Release

on:
  release:
    types:
      - released

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Build binaries
        uses: ./.github/actions/build-binaries
        with:
          snapshot: false
          release: true
